### ISSUE TITLE
Error when downloading or building the docker image

### ISSUE THREAD

**Issue by michyweb** [dolevf/Damn-Vulnerable-GraphQL-Application#11]
**When building the image:**

Damn-Vulnerable-GraphQL-Application# docker build -t dvga .
![image](https://user-images.githubusercontent.com/18649677/108818281-0cd6d880-75b1-11eb-8695-5d060fb7d92f.png)
 ---> Running in ab8d18a1f4c3
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
ERROR: unable to select packages:
  curl (no such package):
    required by: world[curl]
The command '/bin/sh -c apk add --update curl' returned a non-zero code: 1

**When downloading the image:**

Damn-Vulnerable-GraphQL-Application# docker run -t -p 5000:5000 -e WEB_HOST=0.0.0.0 dvga
Unable to find image 'dvga:latest' locally
docker: Error response from daemon: pull access denied for dvga, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by dolevf** [comment]
Hi,

Did you run the following commands?

1. `docker pull dolevf/dvga`
2. `docker run -t -p 5000:5000 -e WEB_HOST=0.0.0.0 dolevf/dvga`

**Comment by michyweb** [comment]
You're right I didn't see it in the README, thank you, it worked

**Comment by dolevf** [comment]
I updated the README to make it a little clearer as a result of this submission, so thank **you** 👍
