### ISSUE TITLE
400 errors in response when queryng

### ISSUE THREAD

**Issue by prohk** [dolevf/Damn-Vulnerable-GraphQL-Application#12]
![image](https://user-images.githubusercontent.com/37725167/109782219-989cd480-7c43-11eb-9f76-4b02e0cb7bfd.png)
what's wrong with it？Other queries are also such problems...

**Comment by prohk** [comment]
![image](https://user-images.githubusercontent.com/37725167/109782486-e9143200-7c43-11eb-8c49-498330eae7e2.png)
Error reported by the console

**Comment by dolevf** [comment]
This is intended behaviour because of hardening procedures

**spoiler alert**

Check your cookies.

**Comment by sekhar-arecabay** [comment]
Hi @dolevf 

Even im seeing same issue. For majority of the requests in Beginner mode (im sending requests with X-DVGA-MODE: Beginner header attached) im getting GraphiQL Access Rejected. 

Even i tried to add/modify cookies as per set-cookie in response for next requests but im seeing same result

**Comment by sekhar-arecabay** [comment]
got it @dolevf :) nice

@prohk checkout the env cookie to be more specific, u should be able to figure out

**Comment by prohk** [comment]
cool , thks bro

**Comment by dolevf** [comment]
enjoy, closing
