### ISSUE TITLE
Minor incongruences

### ISSUE THREAD

**Issue by halfluke** [dolevf/Damn-Vulnerable-GraphQL-Application#15]
When you create a paste:
- no matter if you specify public or private, it always goes to the private pastes
- no matter if you specify "burn" true or false, it always returns "false" (although I'm not sure what difference there should be)
- the title you specify is ignored
![image](https://user-images.githubusercontent.com/33841708/111224832-e1a34000-85d6-11eb-8903-7cb8ae3f99ff.png)

- Audit log is mostly empty
![image](https://user-images.githubusercontent.com/33841708/111226928-b79f4d00-85d9-11eb-8d7b-a4d62200119e.png)

**Comment by dolevf** [comment]
All of these were fixed in version 1.2.3. :1st_place_medal: to you for reporting these.

As a token of appreciation, I added a new section of contributors/thank you and listed you under it.

https://github.com/dolevf/Damn-Vulnerable-GraphQL-Application#contributors
