### ISSUE TITLE
Create Authentication & Authorization layer

### ISSUE THREAD

**Issue by dolevf** [dolevf/Damn-Vulnerable-GraphQL-Application#16]
**Add authentication and authorization layer**
- New roles: Ideally 2, normal user and administrator

This will give us more options to introduce Authorization layer vulnerabilities.

**Comment by plasmak** [comment]
Added in dev branch an authorization layer based on a jwt token claim thus introducing 3 roles: user, moderator and admin. If the PR review is accepted by Connor, then this issue can be closed :)

**Comment by dolevf** [comment]
2.1.0
