### ISSUE TITLE
Version 1.3.1 isn't available from Docker Hub

### ISSUE THREAD

**Issue by jgmoss** [dolevf/Damn-Vulnerable-GraphQL-Application#19]
Hello,

The Docker Hub image hasn't been updated in 6 months. Is it possible to push the newest version to Docker Hub?

Thank you for making such a great tool!

**Comment by dolevf** [comment]
Yes, I've been meaning to get to it this week. sorry about that!

**Comment by dolevf** [comment]
you can now run `docker pull dolevf/dvga:latest` and get version 1.3.1.
