### ISSUE TITLE
Python version 3.10 breaks the application

### ISSUE THREAD

**Issue by chovanecadam** [dolevf/Damn-Vulnerable-GraphQL-Application#34]
Hello, the application attempts to import `Mapping` from `collections` and fails to run:

```
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)
```

This is due to a [change](https://docs.python.org/3/whatsnew/3.10.html) in Python3.10:

```
Remove deprecated aliases to [Collections Abstract Base Classes](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes) from the [collections](https://docs.python.org/3/library/collections.html#module-collections) module. (Contributed by Victor Stinner in [bpo-37324](https://bugs.python.org/issue?@action=redirect&bpo=37324).)
```

The docker container works without any issues. Could we add this constraint about the Python version to the readme file?

**Comment by dolevf** [comment]
Thank you for submitting this.

**Comment by dolevf** [comment]
https://github.com/dolevf/Damn-Vulnerable-GraphQL-Application/blob/master/README.md
