### ISSUE TITLE
Can u guys add flags for capture?

### ISSUE THREAD

**Issue by re4sonzy** [dolevf/Damn-Vulnerable-GraphQL-Application#45]

**Comment by dolevf** [comment]
Hello,

Are you referring to CTF flags?

**Comment by re4sonzy** [comment]
> Hello,
> 
> Are you referring to CTF flags?

Yes, that makes things feeling good, just like hacker101 ctf

**Comment by dolevf** [comment]
Never thought about this, but nothing stops you from forking DVGA and introduce a CTF version of it :) we currently don't have a plan introducing it.
