### ISSUE TITLE
resolve_me requires post request

### ISSUE THREAD

**Issue by schoobydrew** [dolevf/Damn-Vulnerable-GraphQL-Application#58]
The resolve_me function in `/master/core/views.py` uses
```python
info.context.json['identity'] = identity
``` 
and if the request does not contain a JSON object ie a GET request the thread will fail throwing a NoneType error.

**Comment by dolevf** [comment]
Hey, when would you use GET in the context of this query?

**Comment by schoobydrew** [comment]
I was manually building queries using curl and up until that function, GET using `/graphql?query=...` worked fine.
Do you think there should be a more graceful error for this or leave it so that DVGA can also teach flexibility while testing?

**Comment by dolevf** [comment]
I was able to reproduce what you said, thanks for that!

There's no harm in handling the error a little better, I will look into that.
