### ISSUE TITLE
Information Disclosure :: Stack Trace Errors

### ISSUE THREAD

**Issue by halfluke** [dolevf/Damn-Vulnerable-GraphQL-Application#60]
Stack trace doesn't seem to be enabled or properly implemented. I checked graphene documentation but tbh I did not understand how to get a proper stack trace. Is there a way to enable a proper stack trace that would also be picked up by graphql-cop?

At the moment:

# Navigate to /graphiql
# Query using invalid syntax and observe the response.
query {
    pastes {
        conteeeent
    }
}

HTTP/1.1 400 BAD REQUEST
Content-Type: application/json
Content-Length: 147
Date: Thu, 01 Sep 2022 11:10:27 GMT

{"errors":[{"message":"Cannot query field \"conteeeent\" on type \"PasteObject\". Did you mean \"content\"?","locations":[{"line":3,"column":9}]}]}

**Comment by dolevf** [comment]
It works for me:

```
{
  "errors": [
    {
      "message": "Cannot query field \"conteeeent\" on type \"PasteObject\". Did you mean \"content\"?",
      "locations": [
        {
          "line": 3,
          "column": 9
        }
      ],
      "extensions": {
        "exception": {
          "stack": [
            "  File \"/home/dvga/.local/lib/python3.7/site-packages/gevent/baseserver.py\", line 34, in _handle_and_close_when_done\n    return handle(*args_tuple)\n",
            "  File 
```

Make sure your DVGA is set to Beginner mode (header: `X-DVGA-MODE`, value: `Beginner`). The unit tests also show how to get to this state:

https://github.com/dolevf/Damn-Vulnerable-GraphQL-Application/blob/da68382220a6a14e35cb4b4dcca47e7ccf55776d/tests/test_vulnerabilities.py#L173-L186

**Comment by halfluke** [comment]
This is weird.
I have just cloned it from scratch and built the Docker image from the clone: the X-DVGA-MODE header is never automatically added, but even if I add it manually, I still get my previous error without any stack trace...

**Comment by halfluke** [comment]
All passed, although I am using python 3.10

└─# python3 -m pytest tests/*                                    
============================================================================================================ test session starts ============================================================================================================
platform linux -- Python 3.10.5, pytest-7.1.2, pluggy-1.0.0+repack
rootdir: /home/halfluke/Documents/Damn-Vulnerable-GraphQL-Application
plugins: anyio-3.6.1
collected 56 items                                                                                                                                                                                                                          

tests/test_args_and_directives.py ..                                                                                                                                                                                                  [  3%]
tests/test_auth.py ....                                                                                                                                                                                                               [ 10%]
tests/test_batching.py ..                                                                                                                                                                                                             [ 14%]
tests/test_cookies.py .                                                                                                                                                                                                               [ 16%]
tests/test_graphiql.py .                                                                                                                                                                                                              [ 17%]
tests/test_graphql.py .                                                                                                                                                                                                               [ 19%]
tests/test_intialize.py ...                                                                                                                                                                                                           [ 25%]
tests/test_introspect.py ...                                                                                                                                                                                                          [ 30%]
tests/test_mode.py ..                                                                                                                                                                                                                 [ 33%]
tests/test_mutations.py .......                                                                                                                                                                                                       [ 46%]
tests/test_queries.py ..............                                                                                                                                                                                                  [ 71%]
tests/test_rollback.py .                                                                                                                                                                                                              [ 73%]
tests/test_vulnerabilities.py ..............                                                                                                                                                                                          [ 98%]
tests/test_websockets.py .                                                                                                                                                                                                            [100%]

============================================================================================================ 56 passed in 3.45s =

**Comment by dolevf** [comment]
So this means stack trace is returned by DVGA, how does your python code look like where you attempt the stack trace?

**Comment by halfluke** [comment]
Python code? what do you mean? I am just using Burp and sending the "conteeent" request as per DVGA Stack trace solution

**Comment by dolevf** [comment]
Can you share a screenshot or information about the settings in Burp?

**Comment by halfluke** [comment]
![image](https://user-images.githubusercontent.com/33841708/187949300-9cd8d14a-4444-463b-a058-90ff60bf8b68.png)

**Comment by dolevf** [comment]
change 

```
POST /graphql HTTP/1.1
```
to

```
POST /graphiql HTTP/1.1
```

Stack tracing is only enabled on the **/graphiql** endpoint, not **/graphql**

**Comment by halfluke** [comment]
damn! you are right!
We have to change graphql-cop as well then :)
There is a pull request waiting, perhaps we should change the stack trace check or add it for /graphiql too?
