### ISSUE TITLE
Authorization Bypass :: GraphQL JWT Token Forge

### ISSUE THREAD

**Issue by halfluke** [dolevf/Damn-Vulnerable-GraphQL-Application#61]
Not sure how this works / how I am supposed to forge a token
I can see how I can get a token via the login mutation, but I can't understand what "forge it for the 'me' query operation" means in this context

**Comment by dolevf** [comment]
You decode and modify the token, then reencode.

**Comment by dolevf** [comment]
with a site such as jwt.io

**Comment by halfluke** [comment]
yes, I did it with jwt_tool, but what happens then? I use the new token for the /me query and the response is:
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 20
Date: Fri, 02 Sep 2022 15:19:17 GMT

{"data":{"me":null}}

I understand that the signature is not checked, but do you mean that if I know another username, I can impersonate that user?

**Comment by dolevf** [comment]
yes, by forging the jwt to have another user in the claims, it would return info on other system users. There are unit tests that show how this is done under the tests folder.

**Comment by halfluke** [comment]
thank you!

**Comment by halfluke** [comment]
Hi Dolev,
sorry for reopening this, but I just want to report that when we query the /me endpoint, either with an original or an altered jwt - it doesn't matter - the password is always returned as ********, except for the original one of the admin user. So only the original password for admin is displayed in clear.

**Comment by dolevf** [comment]
This is intentional - when you change the JWT's `identity` field, you essentially fool the app to think you are authenticated as the admin user, and only the admin user can fetch see the password field (of the currently logged in user, which is also admin when its forged).

The `me` query doesn't take arguments of other users because it just returns current session information

**Comment by halfluke** [comment]
Ah, got it. Thank you
