### ISSUE TITLE
"paste" and "pastes" as defined in the schema should probably be named getPaste and getPastes for consistency

### ISSUE THREAD

**Issue by halfluke** [dolevf/Damn-Vulnerable-GraphQL-Application#63]
As the application issues the query with getPastes as Operation Name:

![image](https://user-images.githubusercontent.com/33841708/194968351-78e73fa9-da7c-4e3e-b1fc-f9ab210c04f6.png)

**Comment by dolevf** [comment]
Hmm, operation names are optional, I don't think there is a particular benefit to renaming the queries to follow the operation names. But nevertheless thanks for raising this.
