### ISSUE TITLE
Postman collection to test Solutions

### ISSUE THREAD

**Issue by meenakshi-dhanani** [dolevf/Damn-Vulnerable-GraphQL-Application#64]
I love the practice and learning I could get from the Damn Vulnerable GraphQL Application. In addition to the Solutions provided and the instructions on the home page, do you think you'd like to support it with a Postman collection? 
This one was convenient for me as I worked alongside the application, the Attack to Learn collection in this public workspace can be [forked](https://www.youtube.com/watch?v=NEkcE1DwNMo) and since this is on a public workspace, it's also open to contributions since the collections are version controlled. 

Let me know what you think of this one. 

[Supporting Postman Collection - Attack to Learn](https://www.postman.com/devrel/workspace/graphql-security-101/collection/14270212-b5875c90-d36e-43f4-8bd7-2c81b556245d?action=share&creator=14270212)

**Comment by dolevf** [comment]
I like this idea. Are you suggesting to have a postman collection with the solutions built into them as part of the repository?

**Comment by dolevf** [comment]
Also, is that something you would like to take on and contribute?

**Comment by dolevf** [comment]
https://github.com/dolevf/Damn-Vulnerable-GraphQL-Application/pull/70
