### ISSUE TITLE
DVGA gets VERY slow when scanned by ZAP

### ISSUE THREAD

**Issue by psiinon** [dolevf/Damn-Vulnerable-GraphQL-Application#69]
A ZAP active scan causes DVGA to run _very_ slowly - I'm currently getting response times of around 2 mins when accessing the top page via curl on the command line.
I know ZAP can put applications under a lot of strain but most do not react this badly 😁 
Tested with OWASP ZAP 2.12.0. Update to get the latest graphql add-on, then import the DVGA graphql definition and start and active scan.

**Comment by dolevf** [comment]
Hello Simon! 

I don't think I've ran ZAP against it before so let me take a closer look into this.

**Comment by dolevf** [comment]
I'm no expert in ZAP so forgive me for my ignorance :) Here is what I did.

I imported the SDL file and provided the endpoint for GraphQL using the import wizard.

After doing this, ZAP immediately started populating the history tab with some mutations and queries. On my machine, most of them were fast with the exception of a few that returned a response after 50-60 seconds, those were specifically  the query `systemUpdate` which adds some `sleep` to simulate some activity, it's part of the ctf-like nature of DVGA (i attached a screenshot).

![Screenshot from 2022-11-30 11-44-07](https://user-images.githubusercontent.com/5857304/204863872-7856a6e9-ddb4-4988-b625-43151a93c7a4.png)


Afterwards, from the left tree navigation bar, I right clicked the site and clicked on Active Scan. While it ran it was sometimes hanging but nothing specifically stood out as abnormal. I see at least 6000+ queries sent and they return pretty quickly, same with mutation writes.

![Screenshot from 2022-11-30 12-06-08](https://user-images.githubusercontent.com/5857304/204863936-46b85072-a583-49a0-aae0-519e763d96e7.png)

Is there a quick way to know how many queries and mutations ZAP runs in total and which ones? my only suspicions is that it might be running that simulated sleep query of `systemUpdate` and that might cause some issues. I've no idea if this is the case though.

**Comment by dolevf** [comment]
@psiinon hey there,

I would love to address any obvious culprits but I am not entirely sure if there is an addressable issue. Is there any data you can share from your scan, such as where exactly it starts hanging and what queries or mutations are executed?
