### ISSUE TITLE
Error in the Solutions page

### ISSUE THREAD

**Issue by zerodayhacker** [dolevf/Damn-Vulnerable-GraphQL-Application#73]
On the **Solutions** page, the **Information Disclosure :: GraphQL Interface** section mentions you can use the Nmap NSE script to enumerate GraphiQL endpoints. The script exits once it finds one endpoint that allows Introspection, so it will not enumerate all endpoints.

**Comment by dolevf** [comment]
Thanks for the submission, this was removed.
