### ISSUE TITLE
Error when loading the image 

### ISSUE THREAD

**Issue by vicenteh792324** [dolevf/Damn-Vulnerable-GraphQL-Application#77]
Hi buddy ! 

I have a little problem when running the image. I search more about apk with curl related information but i am still stuck with this error. Any idea with the log's showed in the image?

![image](https://github.com/dolevf/Damn-Vulnerable-GraphQL-Application/assets/142704563/edfb3819-c84d-47b7-8c49-2355050f7d40)

**Comment by dolevf** [comment]
Hi there,

I've never ran into this error, but it does indicate it encountered a temporary error. Have you tried it again since?

**Comment by vicenteh792324** [comment]
Your are right buddy, I tried again and it worked perfectly. So, the issue was temporary.
