### ISSUE TITLE
Missing `__init__.py` files in `core` and `db` folder

### ISSUE THREAD

**Issue by thomas-serre-sonarsource** [dolevf/Damn-Vulnerable-GraphQL-Application#80]
Hello!

I noticed that `__init__.py` files do not exist in `core` and `db` folders. Though, `core` is used [as a python package](https://github.com/dolevf/Damn-Vulnerable-GraphQL-Application/blob/552e32591c6b7be9483153931511a3ebd4ace6d7/app.py#L32).
Indeed, this is valid Python, and it will work with a Python interpreter in a version greater than 3.3. 

However, I think adding these files would be a better practice to indicate that `core` and `db` are Python packages. 
First, packages without `__init__.py` files or [namespace package](https://realpython.com/python-namespace-package/) are usually used to organize [multiple packages](https://realpython.com/python-namespace-package/#in-short-python-namespace-packages-are-a-way-to-organize-multiple-packages), which is not the intention here. 
Also, `__init__.py` files are present in similar projects like [for example in skflabs](https://github.com/blabla1337/skf-labs/tree/master/python/Auth-bypass-2/config)

Would it be possible to add `__init__.py` in the `core` and `db` folders so they will be _standard_ python packages? If you agree, I'll create a PR for this.
Thanks!

**Comment by dolevf** [comment]
Hi there. Yes, this is possible!

**Comment by thomas-serre-sonarsource** [comment]
I'll close the issue once the PR is merged ;)
