### ISSUE TITLE
GraphQL belongs to the GraphQL Foundation, not Facebook

### ISSUE THREAD

**Issue by benjie** [dolevf/Damn-Vulnerable-GraphQL-Application#84]
Neat project! I noticed the description says "Facebook's GraphQL technology", but GraphQL was transferred to the GraphQL Foundation in 2019 to be a vendor neutral home for the technology and has evolved significantly since then, so I thought you might like to correct the inaccuracy? Either way, thanks for the work on this project! :raised_hands:

**Comment by dolevf** [comment]
Noted, and thank you Benjie.

How about the current description? feel free to suggest improvements :-)

**Comment by benjie** [comment]
Thanks Dolev! I think you could just remove the parenthesis entirely if you want, but it's fine how it is :heart: 

Here's an alternative, if you were so inclined:

> Damn Vulnerable GraphQL Application is an intentionally vulnerable GraphQL service implementation designed for learning about and practising GraphQL Security.

Either way, happy for you to close the issue :)

**Comment by dolevf** [comment]
I like it - updated the description
