### ISSUE TITLE
requiremnts don't meet specific "gevent" in " requirements.txt"

### ISSUE THREAD

**Issue by epaphrasmakoko** [dolevf/Damn-Vulnerable-GraphQL-Application#85]
Its seems gevent version does not work anymore, This affect from normal python to building and image from docker
please fix the dependencies of python in the requirements.txt
![image](https://github.com/user-attachments/assets/700b33c5-61d6-4a3c-b14a-a3fd85855fda)

**Comment by dolevf** [comment]
Hello,

I just built it from scratch with no issues using the main instructions.

What operating system are you running this one? which python version do you run, and which docker version?

**Comment by dolevf** [comment]
Closing, if you can provide details please reopen
